#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;


class BoardSplitting {
public:
	int numCuts( int leftOver, int desiredLength, int desiredCount, int actualLength)
    {
            if( desiredCount == 0 ) return 0;

            int lenNeeded = desiredLength % actualLength;

            if( lenNeeded == leftOver ) 
                return numCuts( actualLength, desiredLength, desiredCount - 1, actualLength );

            if( leftOver > lenNeeded ) {
                leftOver = lenNeeded - leftOver;
                return 1 + numCuts( leftOver, desiredLength, desiredCount - 1, actualLength );
            }

            else
            {
                lenNeeded -= leftOver;
                leftOver = actualLength - lenNeeded;
                return 2 + numCuts( leftOver, desiredLength, desiredCount - 1, actualLength );
            }
    }

	int minimumCuts(int desiredLength, int desiredCount, int actualLength)
    {
        int curBoard;
        int leftOver = actualLength - desiredLength % actualLength;
        if( leftOver == 0 ) return 0;
        else return 1 + numCuts( leftOver, desiredLength, desiredCount - 1, actualLength );
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, int p0, int p1, int p2, bool hasAnswer, int p3) {
	cout << "Test " << testNum << ": [" << p0 << "," << p1 << "," << p2;
	cout << "]" << endl;
	BoardSplitting *obj;
	int answer;
	obj = new BoardSplitting();
	clock_t startTime = clock();
	answer = obj->minimumCuts(p0, p1, p2);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p3 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p3;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	int p0;
	int p1;
	int p2;
	int p3;
	
	{
	// ----- test 0 -----
	p0 = 5;
	p1 = 4;
	p2 = 4;
	p3 = 3;
	all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	p0 = 6;
	p1 = 100;
	p2 = 3;
	p3 = 0;
	all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	p0 = 500;
	p1 = 5;
	p2 = 1000;
	p3 = 3;
	all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	p0 = 314;
	p1 = 159;
	p2 = 26;
	p3 = 147;
	all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
