#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;


class GolfScore {
public:
	int get_score( string s, int par_value )
	{
		if( s == "triple bogey" ) return 3;
		else if( s == "double bogey" ) return 2;
		else if( s == "bogey" ) return 1;
		else if( s == "par" ) return 0;
		else if( s == "birdie" ) return -1;
		else if( s == "eagle" ) return -2;
		else if( s == "albatross" ) return -3;
		else return 1 - par_value;
	}

	int tally(vector <int> parValues, vector <string> scoreSheet)
	{
		int t_score = 0;
		int t_par = 0;

		for( int i = 0; i < parValues.size(); i++ )
		{
			t_score += get_score( scoreSheet[i], parValues[i] );
			t_par += parValues[i];
		}

		return t_par + t_score;
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, vector <int> p0, vector <string> p1, bool hasAnswer, int p2) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p0[i];
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p1.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p1[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	GolfScore *obj;
	int answer;
	obj = new GolfScore();
	clock_t startTime = clock();
	answer = obj->tally(p0, p1);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p2 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p2;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <int> p0;
	vector <string> p1;
	int p2;
	
	{
	// ----- test 0 -----
	int t0[] = {1,1,1,1,1,1,1,1,1,5,5,5,5,5,5,5,5,5};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	string t1[] = {"bogey","bogey","bogey","bogey","bogey","bogey","bogey","bogey","bogey","eagle","eagle","eagle","eagle","eagle","eagle","eagle","eagle","eagle"};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	p2 = 45;
	all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	int t0[] = {3,2,4,2,2,1,1,1,3,2,4,4,4,2,3,1,3,2};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	string t1[] = {"bogey","double bogey","par","double bogey","double bogey","triple bogey","triple bogey","triple bogey","bogey","double bogey","par","par","par","double bogey","bogey","triple bogey","bogey","double bogey"};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	p2 = 72;
	all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	int t0[] = {3,2,4,2,2,1,1,1,3,2,4,4,4,2,3,1,3,2};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	string t1[] = {"eagle","birdie","albatross","birdie","birdie","par","hole in one","par","eagle","birdie","albatross","albatross","albatross","birdie","eagle","hole in one","eagle","birdie"};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	p2 = 18;
	all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	int t0[] = {4,1,3,3,4,4,1,4,2,3,3,5,4,1,4,4,2,1};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	string t1[] = {"triple bogey","triple bogey","bogey","par","triple bogey","double bogey","triple bogey","triple bogey","par","eagle","bogey","bogey","birdie","par","triple bogey","eagle","triple bogey","triple bogey"};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	p2 = 77;
	all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
